# Generated by Django 3.1 on 2022-01-27 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supervision', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='observation',
            old_name='whenStarted',
            new_name='when_registered',
        ),
    ]
