# Generated by Django 3.1 on 2022-01-27 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervision', '0002_auto_20220127_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='eiermerkeFarge',
            field=models.TextField(blank=True),
        ),
    ]
