# Generated by Django 3.1 on 2022-01-28 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supervision', '0003_auto_20220127_1717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='observation',
            old_name='dodsarsak',
            new_name='dodSaudodsarsak',
        ),
        migrations.RenameField(
            model_name='observation',
            old_name='typeSkade',
            new_name='skadetSautypeSkade',
        ),
    ]
