# Generated by Django 3.1 on 2022-01-28 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supervision', '0004_auto_20220128_1232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='observation',
            old_name='dodSaudodsarsak',
            new_name='dodSauDodsarsak',
        ),
        migrations.RenameField(
            model_name='observation',
            old_name='skadetSautypeSkade',
            new_name='skadetSauTypeSkade',
        ),
    ]
